{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    service: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
{{- end }}
