---
env: dev
image: ""
port: 3000

externalSecret:
  enabled: true

service:
  enabled: true
  type: NodePort

ingress:
  enabled: false
  hostnames: []

resources:
  requests:
    cpu: 200m
  limits:
    memory: 700Mi

# extra environment variables from ConfigMaps like
# envConfig;
#   <ENV_VAR_NAME>:
#     name: <nameOfConfigMap>
#     key: <keyOfValueInConfigMap>
configMapEnv: {}

# extra environment variables from Secrets like
# envSecret;
#   <ENV_VAR_NAME>:
#     name: <nameOfSecret>
#     key: <keyOfValueInSecret>
secretEnv: {}

# extra static environment variables like
# envVars;
#   <ENV_VAR_NAME>: <envVarValue>
statiEnv: {}

readinessProbe:
  initialDelay: 5
  period: 10
  type: httpGet
  path: /

livenessProbe:
  initialDelay: 5
  period: 10
  type: httpGet
  path: /
