# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
{{- if .Values.ingress.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: "{{ .Release.Name }}-tls"
  dnsNames:
    - "{{ .Release.Name }}.{{ .Values.env }}.allstar.dev"
  {{- range $hostname := .Values.ingress.hostnames }}
    - {{ $hostname }}
  {{- end }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end }}
