---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  {{- if eq .Values.env "prod" }}
  replicas: 2
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
      {{- end }}
      containers:
      {{- range $name, $container := .Values.deployment.containers }}
      - name: {{ $name }}
        image: {{ $.Values.image }}
        {{- if $container.resources }}
        resources:
          {{- if $container.resources.requests }}
          requests:
            {{- range $k, $v := $container.resources.requests }}
            {{ $k }}: {{ $v }}
            {{- end }}
          {{- end }}
          {{- if $container.resources.limits }}
          limits:
            {{- range $k, $v := $container.resources.limits }}
            {{ $k }}: {{ $v }}
            {{- end }}
          {{- end }}
        {{- end }}
        env:
        - name: K8S_ENV
          value: {{ $.Values.env }}
        {{- range $k, $v := $container.configMapEnv }}
        - name: {{ $k }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Release.Name }}
              key: {{ $v }}
        {{- end }}
        {{- range $k, $v := $container.secretEnv }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}
              key: {{ $v }}
        {{- end }}
        {{- range $k, $v := $container.staticEnv }}
        - name: {{ $k }}
          value: "{{ $v }}"
        {{- end }}
        {{- if $container.ports }}
        ports:
        {{- range $k, $v := $container.ports }}
        - name: {{ $k }}
          containerPort: {{ $v }}
        {{- end }}
        {{- end }}
        {{- if $container.startupProbe }}
        startupProbe: {{- include "probe" $container.startupProbe  | indent 10 }}
        {{- end }}
        {{- if $container.livenessProbe }}
        livenessProbe: {{- include "probe" $container.livenessProbe  | indent 10 }}
        {{- end }}
        {{- if $container.readinessProbe }}
        readinessProbe: {{- include "probe" $container.readinessProbe | indent 10 }}
        {{- end }}
      {{- end }}
