{{- if .Values.federationSchemaPublishCommand }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-schema-publish"
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-schema-publish"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        command:
          - "/bin/sh"
          - "-xec"
          - "{{ .Values.federationSchemaPublishCommand }}"
        env:
        - name: K8S_ENV
          value: {{ .Values.env }}
        {{- range $k, $v := .Values.deployment.containers.default.configMapEnv }}
        - name: {{ $k }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Release.Name }}
              key: {{ $v }}
        {{- end }}
        {{- range $k, $v := .Values.deployment.containers.default.secretEnv }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}
              key: {{ $v }}
        {{- end }}
        {{- range $k, $v := .Values.deployment.containers.default.staticEnv }}
        - name: {{ $k }}
          value: "{{ $v }}"
        {{- end }}
{{- end }}
