{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    service: {{ .Release.Name }}
  ports:
  {{- range $k, $container := .Values.deployment.containers }}
  {{- range $name, $port := $container.ports }}
  - name: {{ $name }}
    port: {{ $port }}
    targetPort: {{ $port }}
  {{- end }}
  {{- end }}
{{- end }}
